
import React from 'react';
import { 
  LayoutDashboard, 
  Wallet, 
  CreditCard, 
  LineChart, 
  Settings, 
  Plus, 
  Minus, 
  TrendingUp, 
  TrendingDown,
  BrainCircuit,
  Save,
  RotateCcw,
  ArrowRight,
  PieChart,
  PiggyBank,
  X,
  ShieldAlert,
  ShieldCheck,
  GraduationCap,
  AlertTriangle,
  CheckCircle2,
  Gauge,
  Coins,
  Bitcoin,
  Gem,
  Leaf,
  Target,
  Newspaper,
  ExternalLink,
  Activity,
  BarChart3
} from 'lucide-react';

export const Icons = {
  Dashboard: LayoutDashboard,
  Wallet: Wallet,
  CreditCard: CreditCard,
  Chart: LineChart,
  Settings: Settings,
  Plus: Plus,
  Minus: Minus,
  TrendingUp: TrendingUp,
  TrendingDown: TrendingDown,
  AI: BrainCircuit,
  Save: Save,
  Reset: RotateCcw,
  ArrowRight: ArrowRight,
  PieChart: PieChart,
  PiggyBank: PiggyBank,
  Close: X,
  ShieldAlert: ShieldAlert,
  ShieldCheck: ShieldCheck,
  GraduationCap: GraduationCap,
  Warning: AlertTriangle,
  CheckCircle: CheckCircle2,
  Gauge: Gauge,
  Coins: Coins,
  Bitcoin: Bitcoin,
  Gem: Gem,
  Leaf: Leaf,
  Target: Target,
  Newspaper: Newspaper,
  ExternalLink: ExternalLink,
  Activity: Activity,
  BarChart: BarChart3
};
